### ISSUE TITLE
Timestamp issue when upgrading from 0.9.7 to 0.11.5?

### ISSUE THREAD

**Issue by kevinmu** [scalapb/ScalaPB#1276]
Hi, this is probably more of a request for help/assistance than an actual bug.

Like the post says, I am trying to upgrade scalapb from 0.9.7 to 0.11.5. However, I have existing code that instantiates Timestamps (`com.google.protobuf.timestamp.Timestamp`) and I'm having some trouble figuring out how to migrate that code.

If I simply upgrade scalapb and don't change my existing code, I get the following error:
```
java.lang.NoSuchMethodError: 'void com.google.protobuf.timestamp.Timestamp.<init>(long, int)'
```

However, when I try to add the `unknownFields` parameter into the constructor, I get:

```
error: too many arguments (3) for method apply: (seconds: Long, nanos: Int)com.google.protobuf.timestamp.Timestamp in object Timestamp
Note that 'unknownFields' is not a parameter name of the invoked method.
              myDate = Option(Timestamp(seconds = 1, nanos = 0, unknownFields = UnknownFieldSet.empty))))
```

I found https://github.com/scalapb/ScalaPB/issues/679 which kind of seems related, but I was having some trouble deciphering the conversation there. Would you happen to have some advice on how to resolve this issue? Thanks so much for your help!

**Comment by thesamet** [comment]
Hi @kevinmu , it looks like one of the library dependencies of your project was not upgraded to ScalaPB 0.11.x, so some of your project code is compiled for ScalaPB 0.9.x, and some of it for ScalaPB 0.11.x. If you see the stack trace for the "NoSuchMethodError" it might suggest which dependency is the one that needs upgrading to ScalaPB 0.11.x.

If you are using sparksql-scalapb or scalapb-json4s then these pages contain tables of the versions that are compiled to work with ScalaPB 0.11.x: https://scalapb.github.io/docs/sparksql and https://scalapb.github.io/docs/json . It could also be that the dependency that causes it is something else, or a subproject within your project.

**Comment by thesamet** [comment]
Closing due to inactivity, if this issue is still relevant, feel free to respond here again and I can re-open.
