### ISSUE TITLE
Spark 3.3 NoSuchMethodErorr

### ISSUE THREAD

**Issue by larssk** [scalapb/ScalaPB#1488]
Any tips on how to use scalapb with Spark 3.3 ? We get NoSuchMethodError when deserializing. Works with 3.2.0. 

`Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.spark.sql.catalyst.expressions.objects.Invoke.<init>(org.apache.spark.sql.catalyst.expressions.Expression, java.lang.String, org.apache.spark.sql.types.DataType, scala.collection.Seq, scala.collection.Seq, boolean, boolean)'`

**Comment by thesamet** [comment]
Hi @larssk , a version that supports Spark 3.3 was only released yesterday (as a fix for this ticket). Please make sure you use the right version of sparksql-scalapb according to the list here: https://scalapb.github.io/docs/sparksql/#setting-up-your-project

**Comment by larssk** [comment]
Thanks for the update ! Looks like this triggers a new issue: Task not serializable exception 
`Caused by: java.io.NotSerializableException: scalapb.descriptors.FieldDescriptor`

Similar to issue [278](https://github.com/scalapb/sparksql-scalapb/issues/278) but I couldn't figure out the fix for it. 

Tested with 
`
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.1.0")
addSbtPlugin("com.thesamet" % "sbt-protoc" % "1.0.6")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.11.13"
`

`
scalaVersion := "2.12.13"
val sparkVersion = "3.3.0"
libraryDependencies += "com.thesamet.scalapb" %% "sparksql33-scalapb0_11" % "1.0.2"
`

`
Serialization stack:
	- object not serializable (class: scalapb.descriptors.FieldDescriptor, value: )
	- element of array (index: 4)
	- array (class [Ljava.lang.Object;, size 10)
	- element of array (index: 1)
	- array (class [Ljava.lang.Object;, size 3)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.sql.execution.WholeStageCodegenExec, functionalInterfaceMethod=scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/sql/execution/WholeStageCodegenExec.$anonfun$doExecute$4$adapted:(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodeAndComment;[Ljava/lang/Object;Lorg/apache/spark/sql/execution/metric/SQLMetric;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, numCaptured=3])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
`

**Comment by thesamet** [comment]
Please provide a minimal example to reproduce the issue, ideally this can be done in a fork of https://github.com/thesamet/sparksql-scalapb-test or a failing test under the `sparksql-scalapb/src/test/` directory in this repo.

**Comment by larssk** [comment]
https://github.com/thesamet/sparksql-scalapb-test/compare/master...larssk:sparksql-scalapb-test-spark33:master

**Comment by larssk** [comment]
Works on Spark 3.3.2. Fails on Spark 3.3.0, with java.io.NotSerializableException. 

Command to execute: 
```
spark-3.3.0-bin-hadoop3/bin/spark-submit --jars . --class myexample.RunDemo target/scala-2.12/sparksql-scalapb-test-spark33-assembly-1.0.0.jar
```

**Comment by larssk** [comment]
I've updated the description in order to reproduce the issue: 
https://github.com/larssk/sparksql-scalapb-test-spark33/blob/master/README.md

I get the same error locally as on dataproc (which is unfortunately limited to Spark 3.3.0).

**Comment by thesamet** [comment]
Hi @larssk , thanks for creating an example - I was able to reproduce. As far as I can tell this is a Spark bug that has been fixed. We'd have to wait for dataproc to support latest version.
