### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hacetin** [scalapb/ScalaPB#1685]
When do you plan the next release? I see plans for new release in https://github.com/scalapb/ScalaPB/blob/master/CHANGELOG.md 

We need it because of two reasons:
-  `scalapb-validate:-core0.3.5` fails to build with `scalapb:0.11.5`, so version upgrades may help. Some errors:
    ```
    [Error] /Users/.../build/generated/source/proto/main/scalapb/com/google/protobuf/descriptor/FeatureSet.scala:486:108: type StringFieldValidation is not a member of object com.google.protobuf.DescriptorProtos.FeatureSet
    [Error] /Users/.../build/generated/source/proto/main/scalapb/com/google/protobuf/descriptor/FieldOptions.scala:853:47: type mismatch;
      found   : com.google.protobuf.DescriptorProtos.Edition => com.google.protobuf.DescriptorProtos.FieldOptions.EditionDefault.Builder
      required: String => ?
    [Error] /Users/.../build/generated/source/proto/main/scalapb/com/google/protobuf/descriptor/FileDescriptorProto.scala:293:45: type mismatch;
      found   : com.google.protobuf.DescriptorProtos.Edition => com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder
      required: String => ?
    ```
- To use protobuf  java v4

**Comment by thesamet** [comment]
Closing due to inactivity.
