### ISSUE TITLE
Limit the number of breaking changes in 0.10.x

### ISSUE THREAD

**Issue by bjaglin** [scalapb/ScalaPB#721]
Even though 0.10.x is expected a breaking change release, some changes could be made non-breaking by maintaining a compatibility layer (deprecated methods), so that some plugins built against 0.9.x continue to work with 0.10.x, allowing advanced users to test 0.10.x features early and provide more feedback during the ScalaPB milestone/RC phases.

As a concrete example, https://github.com/akka/akka-grpc/blob/v0.7.3/codegen/src/main/scala/akka/grpc/gen/scaladsl/Service.scala#L38 triggers a `java.lang.NoSuchMethodError: scalapb.compiler.DescriptorImplicits$FileDescriptorPimp.scalaPackageName()Ljava/lang/String;` as of https://github.com/scalapb/ScalaPB/commit/2c77a0a3c740168c03b08075e630b43553212ca4#diff-010753e90c409f25d80093154f1eda1fL902-L904, something that could quite easily.

There might be more obstacles down the line though, some of which cannot easily be mitigated, so this might be a vain effort.

**Comment by thesamet** [comment]
I added `FileDescriptor.scalaPackageName` and `Descriptor.scalaTypeName` for binary and source compatibility with earlier version. There are more breakages in DescriptorImplicits but I determined that this is sufficient for fs2-grpc and akka-grpc. If there's anything that can be additionally reintroduced to help, don't hesitate to let me know.
