### ISSUE TITLE
Example Program Does Not Compile With Scala 2.12

### ISSUE THREAD

**Issue by mslinn** [scalapb/ScalaPB#258]
The example program runs fine as shipped. However, if I also update the SBT Plugin to 0.99.6, problems arise:

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.6")

libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.5.47"
```

This is my `build.sbt`:

```
import com.trueaccord.scalapb.compiler.Version.scalapbVersion

scalaVersion := "2.11.8"

PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value
)

libraryDependencies ++= Seq(
  // For finding google/protobuf/descriptor.proto
  "com.trueaccord.scalapb" %% "scalapb-runtime" % scalapbVersion % "protobuf"
)
```

Using Ubuntu 16.04 here are the errors:

```
$ python --version
Python 2.7.12+

$ sbt run
[info] Loading global plugins from /home/mslinn/.sbt/0.13/plugins
[info] Updating {file:/home/mslinn/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /var/work/protobuf/ScalaPB/examples/project
[info] Updating {file:/var/work/protobuf/ScalaPB/examples/project/}examples-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to examples (in build file:/var/work/protobuf/ScalaPB/examples/)
[info] Compiling 2 protobuf files to /var/work/protobuf/ScalaPB/examples/target/scala-2.11/src_managed/main
[info] Compiling schema /var/work/protobuf/ScalaPB/examples/src/main/protobuf/custom_options/my_opts.proto
[info] Compiling schema /var/work/protobuf/ScalaPB/examples/src/main/protobuf/custom_options/use_opts.proto
protoc-jar: protoc version: 320, detected platform: linux/amd64
protoc-jar: executing: [/tmp/protocjar2186948381016193919/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge1439530316382240761, --scala_out=grpc:/var/work/protobuf/ScalaPB/examples/target/scala-2.11/src_managed/main, -I/var/work/protobuf/ScalaPB/examples/src/main/protobuf, -I/var/work/protobuf/ScalaPB/examples/target/protobuf_external, /var/work/protobuf/ScalaPB/examples/src/main/protobuf/custom_options/my_opts.proto, /var/work/protobuf/ScalaPB/examples/src/main/protobuf/custom_options/use_opts.proto]
[info] Compiling protobuf
[info] Protoc target directory: /var/work/protobuf/ScalaPB/examples/target/scala-2.11/src_managed/main
[info] Compiling 7 Scala sources to /var/work/protobuf/ScalaPB/examples/target/scala-2.11/classes...
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:7: type mismatch;
[error]  found   : com.google.protobuf.DescriptorProtos.FileOptions
[error]  required: com.google.protobuf.descriptor.FileOptions
[error]       use_opts.UseOptsProto.descriptor.getOptions) == Some("hello!"))
[error]                                        ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:11: type mismatch;
[error]  found   : com.google.protobuf.DescriptorProtos.MessageOptions
[error]  required: com.google.protobuf.descriptor.MessageOptions
[error]       use_opts.OneMessage.descriptor.getOptions).get == 
[error]                                      ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:17: type mismatch;
[error]  found   : com.google.protobuf.DescriptorProtos.FieldOptions
[error]  required: com.google.protobuf.descriptor.FieldOptions
[error]       numberField.getOptions) == Seq(
[error]                   ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:24: object Implicits is not a member of package com.trueaccord.scalapb
[error]     import com.trueaccord.scalapb.Implicits._
[error]                                   ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:26: value extension is not a member of com.google.protobuf.DescriptorProtos.FileOptions
[error]     assert(use_opts.UseOptsProto.descriptor.getOptions.extension(
[error]                                                        ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:29: value extension is not a member of com.google.protobuf.DescriptorProtos.MessageOptions
[error]     assert(use_opts.OneMessage.descriptor.getOptions.extension(
[error]                                                      ^
[error] /var/work/protobuf/ScalaPB/examples/src/main/scala/custom_options/Main.scala:33: value extension is not a member of com.google.protobuf.DescriptorProtos.FieldOptions
[error]     assert(numberField.getOptions.extension(
[error]                                   ^
[error] 7 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed Mar 23, 2017 3:14:56 PM
```

I'd really like this to work with Scala 2.12.1, but I could not find a combination of dependencies that would run the example program.

**Comment by thesamet** [comment]
Based on the compile errors, it looks like the runtime you had was 0.6.0-pre-x rather than 0.5.47. In any case, I updated the example project to work with 0.6.0-pre-2. I had no issue changing it to use Scala 2.12.1 - can you try and let me know if there is any outstanding issue?

**Comment by mslinn** [comment]
No change. I checked out the project onto a new machine. The problem remains. BTW, it would be a good idea to add `project/build.properties` to the example
